import os
import time
import argparse
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import wandb

from src.model import CVFUNet

class PrecomputedFiberDataset(Dataset):
    def __init__(self, data_dir: str):
        self.data_dir = data_dir
        self.files = [f for f in os.listdir(data_dir) if f.endswith('.pt')]
        if len(self.files) == 0:
            raise FileNotFoundError(f"No .pt files found in {data_dir}")

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        # Directly load the pre-computed mathematical tensors from disk
        file_path = os.path.join(self.data_dir, self.files[idx])
        data = torch.load(file_path, weights_only=True)
        return data['volume'], data['targets']

class MaskedVectorLoss(nn.Module):
    def __init__(self, vector_weight: float = 1.0):
        super().__init__()
        self.mse = nn.MSELoss(reduction='none')
        self.vector_weight = vector_weight

    def forward(self, pred, target):
        pred_edt, pred_vec = pred[:, 0:1], pred[:, 1:4]
        targ_edt, targ_vec = target[:, 0:1], target[:, 1:4]

        loss_edt = self.mse(pred_edt, targ_edt).mean()

        mask = (targ_edt > 0.0).float()
        loss_vec_raw = self.mse(pred_vec, targ_vec) * mask
        
        mask_sum = mask.sum() + 1e-8 
        loss_vec = loss_vec_raw.sum() / mask_sum

        return loss_edt + self.vector_weight * loss_vec

def train_model(gpus: str, data_dir: str):
    if gpus:
        os.environ["CUDA_VISIBLE_DEVICES"] = gpus
    else:
        os.environ["CUDA_VISIBLE_DEVICES"] = ""

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    num_gpus_available = torch.cuda.device_count()
    
    print(f"Executing on: {device}")
    if device.type == 'cuda':
        print(f"Allocated GPUs: {num_gpus_available} (Logical IDs: {list(range(num_gpus_available))})")

    base_batch_size_per_gpu = 4
    batch_size = base_batch_size_per_gpu * max(1, num_gpus_available)
    epochs = 50
    lr = 1e-4
    vector_loss_weight = 5.0

    # <-- W&B Initialization -->
    wandb.init(
        project="fibras-cvfunet",
        config={
            "global_batch_size": batch_size,
            "base_batch_size_per_gpu": base_batch_size_per_gpu,
            "epochs": epochs,
            "learning_rate": lr,
            "vector_loss_weight": vector_loss_weight,
            "num_gpus": num_gpus_available,
            "data_dir": data_dir
        }
    )

    # Point to the isolated splits generated by the offline script
    train_dir = os.path.join(data_dir, "train")
    val_dir = os.path.join(data_dir, "val")
    
    train_ds = PrecomputedFiberDataset(train_dir)
    val_ds   = PrecomputedFiberDataset(val_dir)

    # High-Throughput DataLoader setup
    train_loader = DataLoader(
        train_ds, 
        batch_size=batch_size, 
        shuffle=True, 
        num_workers=8,           # Parallel file reads
        pin_memory=True,         # Locks RAM pages for fast async GPU transfer
        prefetch_factor=4,       # Queues 4 batches per worker ahead of time
        persistent_workers=True  # Avoids process teardown/spinup overhead per epoch
    )
    
    val_loader = DataLoader(
        val_ds, 
        batch_size=batch_size, 
        shuffle=False, 
        num_workers=8,
        pin_memory=True,
        prefetch_factor=4,
        persistent_workers=True
    )

    model = CVFUNet(in_channels=1, base_filters=16)

    if num_gpus_available > 1:
        model = nn.DataParallel(model)
        
    model = model.to(device)
    
    criterion = MaskedVectorLoss(vector_weight=vector_loss_weight)
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-5)
    
    # Initialize Mixed Precision Scaler
    scaler = torch.amp.GradScaler('cuda') if device.type == 'cuda' else None

    wandb.watch(model, criterion, log="all", log_freq=20)
    
    best_val_loss = float('inf')
    os.makedirs("weights", exist_ok=True)

    print("\nStarting Training Loop...")
    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        t0 = time.time()
        
        for batch_idx, (inputs, targets) in enumerate(train_loader):
            # non_blocking=True allows the transfer to overlap with compute
            inputs = inputs.to(device, non_blocking=True)
            targets = targets.to(device, non_blocking=True)
            
            optimizer.zero_grad(set_to_none=True)
            
            if scaler:
                # AMP Block: Casts forward pass to bfloat16 for double throughput
                with torch.amp.autocast('cuda', dtype=torch.bfloat16):
                    outputs = model(inputs)
                    loss = criterion(outputs, targets)
                    if num_gpus_available > 1:
                        loss = loss.mean()
                
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                outputs = model(inputs)
                loss = criterion(outputs, targets)
                if num_gpus_available > 1:
                    loss = loss.mean()
                loss.backward()
                optimizer.step()
            
            train_loss += loss.item()
            
            if batch_idx % max(1, (len(train_loader)//5)) == 0:
                print(f"Epoch [{epoch+1}/{epochs}] Batch [{batch_idx}/{len(train_loader)}] Loss: {loss.item():.4f}")

        train_loss /= len(train_loader)
        
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for inputs, targets in val_loader:
                inputs = inputs.to(device, non_blocking=True)
                targets = targets.to(device, non_blocking=True)
                
                if scaler:
                    with torch.amp.autocast('cuda', dtype=torch.bfloat16):
                        outputs = model(inputs)
                        loss = criterion(outputs, targets)
                        if num_gpus_available > 1:
                            loss = loss.mean()
                else:
                    outputs = model(inputs)
                    loss = criterion(outputs, targets)
                    if num_gpus_available > 1:
                        loss = loss.mean()
                        
                val_loss += loss.item()
                
        val_loss /= len(val_loader)
        t_elapsed = time.time() - t0
        
        wandb.log({
            "epoch": epoch + 1,
            "train_loss": train_loss,
            "val_loss": val_loss,
            "epoch_time_seconds": t_elapsed
        })
        
        print(f"-> Epoch {epoch+1} Summary: Train: {train_loss:.4f} | Val: {val_loss:.4f} | Time: {t_elapsed:.1f}s")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            state_dict = model.module.state_dict() if num_gpus_available > 1 else model.state_dict()
            save_path = f"weights/cvfunet_best.pth"
            torch.save(state_dict, save_path)
            
            wandb.save(save_path)
            print("   [Model Checkpoint Saved & Synced to W&B]")

    wandb.finish()
    print("Training Complete.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train CVFUNet on Precomputed Synthetic Fibers")
    parser.add_argument('--gpus', type=str, default="0", 
                        help='Comma-separated string of GPU IDs (e.g., "0,1"). Pass "" to run on CPU.')
    parser.add_argument('--data_dir', type=str, required=True, 
                        help='Path to the directory containing the precomputed dataset (should contain train and val subfolders).')
    args = parser.parse_args()
    
    train_model(args.gpus, args.data_dir)